### ISSUE TITLE
problem about directory

### ISSUE THREAD

**Issue by GeneZC** [zhongjn/gomokuer#1]
'..' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by zhongjn** [comment]
用cmd时去掉../

**Comment by GeneZC** [comment]
py_network指向null    "Error: Failed to init network"

**Comment by zhongjn** [comment]
python+pytorch可以正常运行吗？

**Comment by GeneZC** [comment]
可以的 在你的电脑上运行正常是吗

**Comment by GeneZC** [comment]
最后解决了：要将模型转为在cpu上运行
