### ISSUE TITLE
编译到Linux上运行出现段错误

### ISSUE THREAD

**Issue by GeneZC** [zhongjn/gomokuer#2]
将gomokuer程序在linux上编译并运行会在model.evaluate()返回policy和value,即pytuple_getitem()时内存溢出

**Comment by Kekwi** [comment]
> 将gomokuer程序在linux上编译并运行会在model.evaluate()返回policy和value,即pytuple_getitem()时内存溢出

哥们儿 你在linux上编译成功了吗？能大概说一下过程吗？
