### ISSUE TITLE
有关virtual loss的使用

### ISSUE THREAD

**Issue by GeneZC** [zhongjn/gomokuer#5]
https://github.com/zhongjn/gomokuer/blob/f44a6f3389b9a97647ce3c8fef17d0363cdb609b/search.cpp#L506
为什么没有使用多线程的蒙特卡洛树搜索，但却使用了virtual loss?

**Comment by GeneZC** [comment]
仔细读了一下，发现并没有用到，作者之前是有做过多线程蒙特卡洛树搜索的实验吗？如果有，效果如何呢？

**Comment by tigert1998** [comment]
多线程不一定好吧。zhongjn写的是async + sequential的mcts
